language: python
dist: xenial
addons:
  apt:
    sources:
      - docker-xenial
    packages:
    - docker
python:
- 3.7.3
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run flake8 canapea test
- poetry run pytest --cov=canapea tests/
